friend_list = ['გიორგი', 'ნინო', 'ნიკა', 'თეა', 'ლევანი', 'გიორგი', 'ნინო', 'ნიკა', 'თეა', 'ლევანი']
print(friend_list[0])
print(friend_list[1])
print(friend_list[2])
print(friend_list[3])
print(friend_list[4])
print(friend_list[5])
print(friend_list[6])
print(friend_list[7])
print(friend_list[8])
print(friend_list[9])
